name: playground_presentation
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: 2.0.0 # http client
  rxdart: ^0.20.0
  shared_preferences: ^0.4.2
  flutter_staggered_grid_view: 0.2.7
  percent_indicator: ^1.0.14
  image_picker: 0.5.0+9
  flutter_advanced_networkimage: 0.4.15
  flutter_picker: 1.0.10
  flutter_screenutil: ^0.4.2
  audioplayers: 0.10.1
  transformer_page_view: ^0.1.6
  cached_network_image: ^0.7.0
  speech_bubble: ^0.0.5
  flare_flutter: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/flare/PlayPause1.flr
    - lib/assets/flare/PlayPause.flr
    - lib/assets/flare/PlayPauseLoop.flr
    - lib/assets/flare/ForwardWind.flr
    - lib/assets/images/play.png
    - lib/assets/images/pause.png
    - lib/assets/images/forward.png
    - lib/assets/images/backward.png
    - lib/assets/images/flutter.png

